// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2pr90Zy3DIt7IRfG-WHI-_N0dEx5fxh0',
    appId: '1:52665304160:web:c425ed52e6e7b06adaaf05',
    messagingSenderId: '52665304160',
    projectId: 'kjri-self-report-app',
    authDomain: 'kjri-self-report-app.firebaseapp.com',
    storageBucket: 'kjri-self-report-app.appspot.com',
    measurementId: 'G-F41Z5F6P2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBHskR-fM0O-REUXoNYIOkvb3-Lqcj3DM',
    appId: '1:52665304160:android:68b807f3fe61e33fdaaf05',
    messagingSenderId: '52665304160',
    projectId: 'kjri-self-report-app',
    storageBucket: 'kjri-self-report-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Db-2AyF-rZ7f-hzsU9F6V0PXs1u4AtI',
    appId: '1:52665304160:ios:f2ecbd14b48d9ee2daaf05',
    messagingSenderId: '52665304160',
    projectId: 'kjri-self-report-app',
    storageBucket: 'kjri-self-report-app.appspot.com',
    iosBundleId: 'com.example.selfReportApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Db-2AyF-rZ7f-hzsU9F6V0PXs1u4AtI',
    appId: '1:52665304160:ios:f2ecbd14b48d9ee2daaf05',
    messagingSenderId: '52665304160',
    projectId: 'kjri-self-report-app',
    storageBucket: 'kjri-self-report-app.appspot.com',
    iosBundleId: 'com.example.selfReportApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2pr90Zy3DIt7IRfG-WHI-_N0dEx5fxh0',
    appId: '1:52665304160:web:d044e5b164096aa0daaf05',
    messagingSenderId: '52665304160',
    projectId: 'kjri-self-report-app',
    authDomain: 'kjri-self-report-app.firebaseapp.com',
    storageBucket: 'kjri-self-report-app.appspot.com',
    measurementId: 'G-K6LC98BQ4V',
  );

}