name: self_report_application
description: An Onboarding Self Report application created by the Consulate General of Indonesia.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.7
  open_file: ^3.2.1
  path_provider: ^2.0.5
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.2
  cloud_firestore: ^5.2.0
  firebase_app_check: ^0.3.0+5
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  open_file: ^3.5.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - images/ListImage.png
    - images/logo.png
    - images/ThumbsUp.jpg
    - images/info-button.svg
    - images/data-active.svg
    - images/identitas-active.svg
    - images/kontak-active.svg
    - images/tujuan-active.svg

  fonts:
  - family: Source Sans Pro
    fonts:
      - asset: fonts/SourceSansPro-Regular.ttf
      - asset: fonts/SourceSansPro-Italic.ttf
        style: italic
      - asset: fonts/SourceSansPro-Bold.ttf
        weight: 700
      - asset: fonts/SourceSansPro-Semibold.ttf
        weight: 600
